version: "3"

services:
  #frontend
  #surveys
  survey_storage:
    image: mongo:latest
    ports:
      - "27017:27017"
  #votes
  vote_queue:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
  #vote_worker
  #vote_storage