version: "3"

services:
  #frontend
  #surveys
  survey_storage:
    image: mongo
    ports:
      - "27017:27017"
  #votes
  vote_queue:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
  #vote_worker
  vote_storage:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - ./init/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin